version: "3.5"
services:
  webpacker:
    build: .
    env_file:
      - ./docker/.env_dev
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - '3035:3035'
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./docker/.env_dev
    command: ./docker/start.sh
    volumes:
      - .:/app
      - bundle:/bundle
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/known_hosts:/etc/ssh/ssh_known_hosts
    ports:
      - "3009:3000"

volumes:
  bundle:
    driver: local
